##Overview

Dear Learner, 

Congratulations, you have studied Python all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

Authors: Albana Celepija, Vinayak Deshpande

###Task 1

We have declared a tuple containing five same elements as following:
T = (‘python’, ‘python’, ‘python’, ‘python’, ‘python’).
Re-write the same code in an optimal/simple way that fetches the same result.

**Solution 1**

In [12]:
# Using multiplication method
# to get five same elements of python, multiply the element by 5
T = ('python',)
print(T*5)

('python', 'python', 'python', 'python', 'python')

In [13]:
# without adding comma, the result or ouput will not be in a tuple-like format
T = ('python')
print(T*5)

pythonpythonpythonpythonpython

###Task 2

Write code to print characters from a string that are present at an even index number.
For example, if your input string is "python", the output characters will be (p,t,o).

**Solution 2**

In [14]:
# Using string
print('Using string')
char = input('Enter a string : ') 
print(char[::2])
print('\n')

Using string
Enter a string : adetoro
aeoo

In [15]:
# Using loop
print('Using loop')
char = input('Enter a string : ')
for index in range(len(char)):
  if index % 2 == 0:
    print(char[index], end = ' ')

Using loop
Enter a string : adetoro
a e o o

### Task 3

Write a function that calculates the average of the elements of the list: 

elements = [5, 7, 4, 9, 2]

Solution 3

In [19]:
# Using normal function
elements = [5, 7, 4, 9, 2]
# creating a robust function that can handle as many list values as possible
# function for calculating average
def avr(num):
  add = sum(num)
  div = len(num)
  average = add/div
  return average  
print('average : ',avr(elements))

average :  5.4

In [20]:
# Using numpy function
import numpy as np
# calculating average / mean
average = np.mean(elements)
print('average : ',average)

average :  5.4

In [21]:
# Using statistics module
import statistics
# list of positive integer numbers
elements = [5, 7, 4, 9, 2]
average = statistics.mean(elements)
print('average : ',average)

average :  5.4

### Task 4
Write code to find if the given year is a leap year or not.

**Solution 4**

Leap years are years where an extra, or intercalary, day is added to the end of the shortest month, February. The intercalary day, February 29, is commonly referred to as leap day.

Leap years have 366 days instead of the usual 365 days and occur almost every four years.

In the Gregorian calendar, three criteria must be taken into account to identify leap years:

1. The year must be evenly divisible by 4;
2. If the year can also be evenly divided by 100, it is not a leap year;
unless...
3. The year is also evenly divisible by 400. Then it is a leap year.

In [24]:
print('Year to be checked must be in the form 2012, 1993, 2089, 2016, etc.')
checkYear = int(input("Enter year to be checked : "))
def check_year(year):
  if (year % 4 == 0 and year % 100 != 0 or year % 400 == 0):
      print("{} is a leap year!".format(year))
  else:
      print("{} isn't a leap year!".format(year))
check_year(checkYear)

Year to be checked must be in the form 2012, 1993, 2089, 2016, etc.
Enter year to be checked : 2090
2090 isn't a leap year!

### Task 5
Given a list of numbers (integers), find the sum of second maximum and second minimum in the following list.

l = [21, 6, 12, 57, 35, 61]

In [25]:
l = [21, 6, 12, 57, 35, 61]
# Python prog to illustrate the following in a list
def find_value(list1):
    length = len(list1)
    list1.sort()
    # after sorting in ascending order, the second element which is also the second minimum has an index of 1
    second_maximum = list1[-2]
    # the second maximum has an index of -2, or the (lenght - 2)
    second_minimum =  list1[1]
    sum = second_maximum + second_minimum
    print("Second Largest element is : ", second_maximum)
    print("Second Smallest element is : ", second_minimum)
    print("Sum of second maximum and second minimum : ", sum)
  
find_value(l)

Second Largest element is :  57
Second Smallest element is :  12
Sum of second maximum and second minimum :  69

##Scores

Each of the tasks is of 2 mark each and the scores will be given accordingly after the notebook review.